ROE-2393 Remove unused sign out page param
companieshouse/overseas-entities-web pull request #1117
Opened 2023-10-05 13:24 UTC by mwestacott

### JIRA link

https://companieshouse.atlassian.net/browse/ROE-2393

### Change description

* This was confusing the implementation required for the Redis cache removal. Neither seem to not be used, so deleting.

### Work checklist

- [ ] Tests added where applicable
- [ ] UI changes meet accessibility criteria

### Merge instructions

We are committed to keeping commit history clean, consistent and linear. To achieve this, this commit should be structured as follows:

```
<type>[optional scope]: <description>
```

and contain the following structural elements:

- fix: a commit that patches a bug in your codebase (this correlates with PATCH in semantic versioning),
- feat: a commit that introduces a new feature to the codebase (this correlates with MINOR in semantic versioning),
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING CHANGE can be part of commits of any type,
- types other than `fix:` and `feat:` are allowed, for example `build:`, `chore:`, `ci:`, `docs:`, `style:`, `refactor:`, `perf:`, `test:`, and others,
- footers other than `BREAKING CHANGE: <description>` may be provided.

2023-10-09 09:25 UTC, markpit approved these changes

2023-10-09 09:28 UTC, markpit requested changes
it looks like url is used in the includes/sign-out-user-banner.html and that is included by layout.html

2023-10-10 08:19 UTC, mwestacott commented
> it looks like url is used in the includes/sign-out-user-banner.html and that is included by layout.html

But the 'url' that was defined here (in the GET method of `sign.out.controller.ts`) and being passed into a template was going into the `sign-out.html` page and even though that template does include the layout and banner, in the case of the sign-out page the sign-out banner is not shown.

2023-10-10 09:37 UTC, markpit approved these changes

2023-10-13 13:29 UTC, dlloyd1-ch approved these changes

2023-10-16 09:07 UTC, merged